### ISSUE TITLE
A couple of design questions

### ISSUE THREAD

**Issue by SukkoPera** [aotta/PiRTOII#3]
I'm working on a modified version of this cart that used the original Pico board (just because I have plenty of those) and I have a few questions on the design. Please note that I don't know anything about the Intellivision. I have bought one some time ago but I have no carts, hence my interest in this project :). So please excuse me if my questions are naive, it's really the first time I look at this stuff:

* I see that pins 8 and 10 are permanently grounded. I can understand it for pin 8, which, according to [the pinout](https://wiki.intellivision.us/index.php/Cartridge_Port) is the EXT_VIDEO input (I guess it's for reducing noise), but not for pin 10: it looks like it is the MCLK _output_, and forcing it to ground doesn't sound good to me. I think it should just be left unconnected. Maybe you wanted to ground pins 6 (EXT_AUDIO) and 8 but you miscounted? Just a thought :).
* Same for pin 20, ROM_DISABLE: why is it grounded?
* The reset circuit does not look correct to me. The BC547 is an NPN transistor and seeing its collector connected to GND is very odd. Besides, I think some resistors should be added in series with the base and collector. Can you please explain the rationale behind it?

Thanks a lot! :)

**Comment by SukkoPera** [comment]
This would be my proposal for the reset circuit:
<img width="424" alt="image" src="https://github.com/aotta/PiRTOII/assets/1316870/d4befabb-dd22-4789-b0ea-8c96bc3aab43">

It's the most common switch circuit based on an NPN transistor, taking advantage of the pull-up resistor which is already inside the console.

(_reset_inty_out_ is the signal coming from the Pico, I've just renamed it)

**Comment by SukkoPera** [comment]
I have finally tested my above proposal for the reset circuit and I can now say that it works perfectly! ;)

I have also verified that grounding the MCLK output is safe, since there is a series resistor inside the console. Still, it puzzles me why this is necessary.

**Comment by aotta** [comment]
Thank @SukkoPera for the alternative design, so close the issue
