### ISSUE TITLE
Incoherent code in "void __not_in_flash_func(core1_main())", in "inty_cart.c" module.

### ISSUE THREAD

**Issue by bricox54** [aotta/PiRTOII#5]
Hello,
There is an unconditional "break" in this "for", "break" should be in "if".
if (hacks>0) {
          for (int i=0; i<maxHacks;i++) {
            if (parallelBus==HACK[i]) {
              dataOut=HACK_CODE[i];
              deviceAddress = true;
            }
            break;
          }
        }

**Comment by aotta** [comment]
Hi, you're right, break position fixed in source

**Comment by bricox54** [comment]
Your welcome !
Congratulations, aotta, for your shared project.
I am putting it into service
